### PR TITLE
ISO-22726-1 compatibility fixes

### LINKED ISSUE #133: coradoc:  partition the output .adoc file based on heading/style levels not working
hello @hmdne 

i am working with an HTML file created by loading a correctly styled .docx (from an SDO) into LibreOffice then "save as" into .html.   additionally from this "save as" 43 images are output along with the single .html file.

the current Gemfile contains

```
# gem "coradoc"
# 20240920
gem "coradoc", git: "https://github.com/metanorma/coradoc"
gem "fontist", git: "https://github.com/hmdne/fontist", ref: "patch-1"
```
coradoc confirmation:

```
PS E:\github\iso-22726-1\conversion> bundle info coradoc
  * coradoc (1.1.2 0c1dbc3)
        Summary: AsciiDoc parser for metanorma
        Homepage: https://www.metanorma.org
        Source Code: https://github.com/metanorma/coradoc
        Path: C:/tools/ruby33/lib/ruby/gems/3.3.0/bundler/gems/coradoc-0c1dbc37e764
        Reverse Dependencies:
                metanorma-plugin-lutaml (0.7.9) depends on coradoc (~> 1.1.1)
```
the command line information shows the following:

```
PS E:\github\iso-22726-1\conversion> bundle exec reverse_adoc --help
Usage: reverse_adoc [options] <file>
    -m, --mathml2asciimath           Convert MathML to AsciiMath
    -o, --output=FILENAME            Output file to write to
    -e, --external-images            Export images if data URI
    -u [pass_through, drop, bypass, raise],
        --unknown_tags               Unknown tag handling (default: pass_through)
    -r, --require RUBYMODULE         Require additional Ruby file
        --track-time                 Track time spent on each step
        --split-sections LEVEL       Split sections up to LEVEL
    -v, --version                    Version information
    -h, --help                       Prints this help

```
using this command:

`bundle exec reverse_adoc --split-sections 1 --external-images -o ./index.adoc ./infile.html`

only `index.adoc` is being created along with 20 renumbered images in the "images" folder. there are no messages displayed during the conversion process.

i am wondering what i am doing wrong with the  --split-sections 1 parameter? 
i have also tried --split-sections=1 but there is no change in output.

is there a hidden parameter that shows processing messages?

thank you.

### PR DESCRIPTION
**Pull request by hmdne**
This PR fixes #133 

In particular, it's concerned about extracting titles if they are nested in ordered lists.

Keep in mind, that this logic is done on coradoc tree, so it'll still be valid once we create a DOCX/ODT input.

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

File: lib/coradoc/element/attribute_list.rb [hunk 1]
```diff
@@ -12,6 +12,16 @@ def initialize(*positional, **named)
         @rejected_named = []
       end
 
+      def inspect
+        "AttributeList: " +
```
Comment (ronaldtse) [inline lib/coradoc/element/attribute_list.rb:16]: self.class.name?

**Comment by ronaldtse** [comment]
Not sure why not yet merged. Merging.
